import React from 'react';

const TextAksobhya = 'Aksobhya ist einer der fünf Dyni-Buddhas. Er herrscht über das reine Land im Osten (Abhirati). Mit seiner rechten Hand berührt er die Erde, seine linke ruht im Schoß. Auf der Hand steht das Donnerkeilzepter Vajra, welches das absolute und unzerstörbar-ewige Prinzip und die Erlösung symbolisiert. Sowohl das Zeigen auf die Erde als auch der Vajra spielen auf den Namen Aksobhya, "der Unerschütterliche" an. In der Malerei ist seine Farbe blau und sein Begleiter ist ein Elefant. Sein Name in China ist Achu, in Tibet Mar-me-msdad.';
const TextAmithaba = 'Amitabha Amitabha ist einer der fünf Dyni-Buddhas. Er herrscht über das reine Land im Westen (Sukhavati). Seine Hände sind in der Geste der Meditation dargestellt. Sein Name bedeutet "Grenzenloses Licht" oder "Der voll unermesslichen Glanzes ist". Jeder, der an ihn glaubt, wird in diesem Land wiedergeboren. Die bloße Nennung seines Namens führt seine Anhänger zur Befreiung von dem endlosen Kreislauf der Wiedergeburten. In der Malerei ist seine Farbe rot, wie die im Westen untergehende Sonne. Keine andere mahayanische Buddhagestalt wird mehr verehrt als Amitabha. Sein Begleiter ist der Pfau, wegen seiner großen Beliebtheit wechselte in der Kunst der Begleiter zu einem Löwen. Sein Name in China ist Dingguang Fo, in Tibet Mi-bskyod-pa in Japan Ashuku Nyorai.';
const TextAmoghasidi = 'Amoghasidhi ist einer der fünf Dyni-Buddhas. Er herrscht über das reine Land im Norden (Paradies ohne Namen). Mit seiner rechten Hand führt er die Geste der Ermutigung aus, während die linke im Schoß ruht auf der das Doppelvajra ruht (das vorhanden sein des Absoluten in allen Himmelsrichtungen). Sein Name bedeutet "dessen Bemühungen Erfolg haben" oder "Der von unfehlbarer Zaubermacht". Sein Begleiter ist der Vogelmensch Garuda. Amoghasiddhi wird besonders in Tibet verehrt, er wird mit einer mehrköpfigen Schlange, Naga, die sich hinter ihm windet, und ihn mit einer gespreizten Halshaut schützend überwölbt. In der Malerei ist seine Farbe grün. Sein Name in Japan ist Fukujoju Nyorai, in Tibet Don-grub.';
const TextShakyamuni = 'Shakyamuni als Buddhastatue in der Meditationsgeste siehe Amitabha , in der Lehrdarlegungsgeste Vairocana , Shakyamuni als Kusumasri ( Shakyamuni hält die Blume in seiner Hand ), Shakyamuni ins Parinirvana eingetreten, mit der Erdberührungsgeste siehe Aksobhya und als Medizinbuddha siehe Bhaisajaguru . In Japan hat er den Namen Shaka Nyorai.'
const TextMaitreya = 'Maitreya: Der Buddha des kommenden Zeitalters, er wartet vom Verlöschen des historischen Buddha Gautama an 5000 Jahre im Tushita Himmel. Dort trägt er den Namen Natha-Maitreya bis er, die bis dahin vergessene Buddhalehre neu in der Welt verkündet. Darstellungen als Maitreya sind Zukunftsvisionen, was auch durch die europäische Sitzhaltung symbolisiert wird. Bei den beiden Statuen war mit Sicherheit die Statue des Maitreya aus dem Nationalmuseum von Korea Vorbild.';
const TextMedizinbuddha = 'Bhaisajaguru ist Shakyamuni als Medizinbuddha . Der historische Buddha hat sich als Arzt für die Leiden der Menschen angesehen. Ab dem 8. Jahrhundert baute sich die tibetische Medizin auf der Ayurvedischen Medizin auf. Die Behandlung zielt darauf ab, ein Gleichgewicht der drei Lebenssäfte, Galle (pitta), Wind (vata) und Schleim (kapha) herzustellen. Der Medizinbuddha wird als Künder, nicht als Heiler angesehen und bekam den Namen Bhaisajaguru. Sein Name in China ist Yaoshi Fo, in Tibet Sman-bla in Japan Yakushi Nyorai.'
const TextRatna = 'Ratnasambhava ist einer der fünf Dyni-Buddhas. Er herrscht über das reine Land im Süden (Prabhavati). Mit seiner rechten Hand führt er die Geste der Wunschgewährung aus, während die linke im Schoß ruht, auf das Cintamani-Juwel steht. In der Malerei wird er gelb dargestellt. Bedeutung des Cintamani Juwel: Juwel der Lehre, das Zauberjuwel Cintamani, der Denkedelstein, der alle Wünsche erfüllt. Sein Name in China ist Baosheng Fo, in Tibet Rin-gbyun, in Japan Hosho Nyorai.'
const TextVairocona = 'Vairocana ist " Der Erleuchtende" oder "Sonnengleiche". Er ist der Ursprung der anderen Dhyani-Buddhas, in deren Mandala ihm der Mittelpunkt zugeordnet ist. Mit seinen Händen führt er entweder die Geste des Predigens (Dharmachakra-Mudra) oder die des Wissens (Bodhyagri-Mudra) aus. Bei der letztgenannten Geste umschließt die linke Hand den Zeigefinger der rechten. Die symbolisiert die Vereinigung von Weisheit und Methode. Vairochanas Symbol ist das Rad der Lehre, und er sitzt auf einem Thron, der von Löwen getragen wird. Er ist das Oberhaupt der Vairochana-Familie und gehört zu Element Äther (oder Raum). Ihm ist die Farbe Weiß zugedacht. In seiner untransformierten Form lebt der Praktizierende in einem Geisteszustand der Verblendung und der Unwissenheit, den es durch Vairochana zu klären gilt. Vairochana steht für die Umwandlung des Geistesgiftes Unwissenheit in eine transzendente, universelle Weisheit, in der alle Erscheinungen als illusionär und leer von eigenständiger Existenz erkannt werden. Sein Name in China ist Palushena, in Tibet Rnam-par-snan-mdsad, in Japan Dainichi Nyorai.';
const TextAvalokitesvara = 'Avalokitesvara Bis zu 1000- Armigen Buddhastatuen. Er ist der Boddhisattva des unendlichen Mitgefühls.Sein grenzenloses Mitgefühl drückt sich in seiner wunderbaren Macht aus, allen Lebewesen zu helfen, welche sich in Gefahr befinden. Es gibt 108 verschiedene Erscheinungsformen von Avalokitesvara. Die bekanntesten sind: -Avalokitesvara als Padmapani (zweiarmig) -Avalokitesvara als Sadaksari-Lokesvara chenrezig(vierarmig) -Avalokitesvara als Ekadasa Mahakarunika-Lokesvara (achtarmig) -Avalokitesvara als Sahasrabuja-Lokesvara (tausendarmig) In China hat er den Namen Guanyin, in Japan Sho Kannon, in Tibet Sryan-ras-gzigs oder Dschenresi. Bodhisattvas sind sogenannte Erleuchtungswesen, die ihren Eintritt ins Nirvana aufschieben, um anderen Wesen zu helfen aus dem Kreislauf der Wiedergeburt zu kommen. Sie nehmen Leid auf und geben von ihren karmischen Verdiensten anderen Wesen ab. Sie verwirklichen Gebefreudigkeit, Sittlichkeit, Geduld, Energie, Meditation und Weisheit.';
const Manjusri = 'Manjusri ist der Bodhisattva der Weisheit. Sein Symbol war ursprünglich ein längerer, sich nach oben verbreitender Stab aus Eisen. Es wurde aber sehr früh von Künstlern durch ein Schwert ersetzt. Durch seine fünfzackige Krone symbolisiert er die spiegelgleiche, wesensgleiche, unterscheidende, alles vollendende, allumfassende transzendente Weisheit. Seine bekanntesten Erscheinungsformen sind: - Manjusri als Arapacana-Manjusri - Manjusri als Simhasana-Manjusri (Manjughosa) - Manjusri als Dharmadhala-Vagisvara-Manjusri In China hat er den Namen Wenshu,in Japan Monju Bosatsu, in Tibet Djam-dpal oder Jampal.'
const NathaMaitreya = 'Natha Maitreya Er ist der Buddha der Zukunft und wird das Dharma auf der Erde neu verkünden. Die Zeit bis zu seinem Erdenauftritt verbringt er im Tusita-Himmel. In Tibet hat er den Namen Jampa dies bedeutet, der Liebevolle.'
const TextTara = 'Tara bedeutet übersetzt "Stern" oder "Befreierin". Tara erscheint in fünf Hauptaspekten, der Weißen, Grünen, Blauen, Gelben und Roten Tara. Bekannt ist auch eine Aufteilung in 21 verschiedene Formen, die als "die regenbogenfarbenen Taras" bezeichnet werden. Jede der Regenbogenfarben steht für eine andere Buddha-Aktivität der Tara. Deshalb wird die Tara auch als Verkörperung der vielfältigen Heilsaktivitäten der Erleuchteten betrachtet. Da sie dadurch unendlich vielen Wesen den Weg zur Erleuchtung eröffnet, nennt man sie auch "Mutter aller Buddhas". Die Weiße Tara ( Sita Tara ) Die Weise Tara bedeutet übersetzt "weiße Retterin". Sie sitzt im vollen Lotossitz, ist weiß und mit den Ornamenten eines Bodhisattvas geschmückt. Ihre rechte Hand formt die Mudra der Gunstgewährung, Zeichen dafür, dass sie in der Lage ist, die Wesen mit allem zu versehen, das sie sich wünschen. Ihre linke Hand bildet die Mudra der Zufluchtsgewährung, ihre Daumen und ihr Ringfinger berühren einander ( Sym- bol für Methode und Weisheit). Die drei übrigen Finger sind zum Zeichen für die drei Zufluchten Buddha, Dharma und Shanga erhoben. Ihr besonderes Merkmal sind ihre sieben Augen. Neben den zwei natürlichen Augen hat sie ein Weisheitsauge auf der Stirn, sowie jeweils ein Auge auf den Handinnenflächen und den Fußsohlen. Wie Avalokitesvara sind die zusätzlichen Augen der Weißen Tara, mit denen sie liebevoll auf die Wesen aller Daseinsbereiche schaut, Zeichen für klarsichtige Weisheit und tiefes Mitgefühl. Die enge Verbindung zum Dhyani Buddha Amitabha ist dadurch zu erkennen.';
const TaraGruen = 'Die Grüne Tara ( Syama Tara ) Die Grüne Tara bedeutet "grüne Retterin". Sie steht in enger Verbindung zum Dhyani Buddha Amoghasiddhi, als dessen Weisheitsgefährtin sie gilt. Die Grüne Tara erscheint in entspannter Sitzhaltung: Sie sitzt, das rechte Bein ausge- streckt und das linke angewinkelt, auf einem Lotos der sich aus einem See erhebt. Der Legende nach soll sie aus einem See von Tränen Avalokitesvaras entstanden sein. Ihre Körperfarbe ist grün, womit Ihre Zugehörigkeit zum Windelement dargestellt wird ( steht für Bewegung ). Das Windelement drückt aus, dass die Grüne Tara ein aktives Prinzip des Mitgefühls darstellt. Durch diese Aktivität werden alle weltlichen und über- weltlichen Handlungen, die zum Wohle anderer sind, voll zur Blüte gebracht. Das angewinkelte Bein symbolisiert ihr Verweilen im Zustand der Nicht-Dualität aller Erscheinungen. Das ausgestreckte Bein verdeutlicht ihre Bereitschaft, jederzeit zum Nutzen der fühlenden Wesen in Aktion zu treten. Ihre linke Hand formt die Mudra der Zufluchtsgewährung. Ihr Daumen und ihr Ringfinger berühren einander als Zeichen für die Vereinigung von Methode und Weisheit. Die drei übrigen Finger sind erhoben als Symbol für die drei Zufluchten Buddha, Dharma und Shanga . TARA Tara bedeutet übersetzt "Stern" oder "Befreierin". Tara erscheint in fünf Hauptaspekten, der Weißen, Grünen, Blauen, Gelben und Roten Tara. Bekannt ist auch eine Aufteilung in 21 verschiedene Formen, die als "die regenbogenfarbenen Taras" bezeichnet werden. Jede der Regenbogenfarben steht für eine andere Buddha-Aktivität der Tara. Deshalb wird die Tara auch als Verkörperung der vielfältigen Heilsaktivitäten der Erleuchteten betrachtet. Da sie dadurch unendlich vielen Wesen den Weg zur Erleuchtung eröffnet, nennt man sie auch "Mutter aller Buddhas".'

const CategoryText = ({ name }) => {
    switch (name) {
        case 'Aksobhya': return <div> {TextAksobhya} </div>;
        case 'Amitabha': return <div> {TextAmithaba} </div>;
        case 'Amoghasidi': return <div> {TextAmoghasidi} </div>;
        case 'Shakyamuni': return <div> {TextShakyamuni} </div>;
        case 'Maitreya': return <div> {TextMaitreya} </div>;
        case 'Medizinbuddha': return <div> {TextMedizinbuddha} </div>;
        case 'Ratnasambhava': return <div> {TextRatna} </div>;
        case 'Vairocana': return <div> {TextVairocona} </div>;
        case 'Avalokitesvara': return <div> {TextAvalokitesvara} </div>;
        case 'Manjusri': return <div> {Manjusri} </div>;
        case 'Natha Maitreya': return <div> {NathaMaitreya} </div>;
        case 'Weiße Tara (Sitatara)': return <div> {TextTara} </div>;
        case 'Gruene Tara (Syamatara)': return <div> {TaraGruen} </div>;
        default: return null;
    }
}

const CategoryTextLayout = ({ name }) => (
    <div 
    className="content"
    style={{
        maxHeight: "200px",
        overflowY: "auto"
    }}>
        <CategoryText name={name} />
    </div>
)


export default CategoryTextLayout;
